rootProject.name = "zelda-mono"

include("infra-lib")
include("account-svc")
include("account-api")
include("company-api")
include("company-svc")
include("mail-api")
include("mail-svc")
include("sms-svc")
include("sms-api")
include("bot-api")
include("bot-svc")
include("ical-svc")
include("whoami-api")
include("whoami-svc")
include("icalc-svc")
include("web-app")
include("faraday")
