spring:
  profiles:
    active: DEV
  application:
    name: saas-web-bi
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password


server:
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: false
  port: 8080
