# application.yml

spring:
  profiles:
    active: DEV
  application:
    name: web-daruk
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/zelda
      username: zelda
      password: zelda
    url: jdbc:postgresql://localhost:5432/zelda
    driver-class-name: "org.postgresql.Driver"

server:
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: false
  port: 8080

sentry:
  dsn: https://4a6a7fbbd55b46c6b6f0ea71d5f52927@o280215.ingest.sentry.io/5228407

daruk:
  jwt:
    secret: "1"
    expired: 600000
