# application.yml

spring:
  profiles:
    active: DEV
  application:
    name: web-daruk

server:
  error:
    whitelabel:
      enabled: false
  undertow:
    accesslog:
      enabled: false
  port: 8080

sentry:
  dsn: https://4a6a7fbbd55b46c6b6f0ea71d5f52927@o280215.ingest.sentry.io/5228407

